# Generated by Django 3.0.5 on 2020-04-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mulvala2b', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
